addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "wN0Ccky6by/Y/RQfGyFWTNKrbe54rJ9K7nuWq8ab1x0tedBC66UHwMaLPZlq+k7yLNmOW7/DAJ93tqBlX5meCzDlAwf8cC2QYQHE9m5FMAWKiDUTerceTEGdcMdP6Os7c8yC8VZ7dTOZlX1W1j5YK2A6ojHfF543CHH9BUgaznKfmHnFxgILkhYhxALLTSw25Im3Ucnf/PFXla/z0eLebnwHTkbPsYs/MTZvvmrGibHywPrbkoYpoMmMWGu+u+/w2JuEDgC7/7JLGltkvkbtpKR4bYg77C66MzIwgF5DjUNmAZ6FBalVrh/9rY0gp7q4ZdoF39Ugg7VufTaL+qCHUutC87pxeHOSrab2ZgcPGc3IlEDj3FFw4Wbx6eCtPIrUJ/M2QGVuppiDALrGGBXrB6Fl77xN/vCxpHNEo047/pVGVBg9q5U0f87fwTieHOFBsVfZWB6luRh6C1aRRuS6OAoqNqNWJAalVHbu7DgI9x2tvd/Vqxh3NiqI96lz+RT5yUhEaPieL0Y609h7MD9O11Z4xoeqmNrp+X7rM/A2tgK8xBgYr71DPigy7o929QaLK27FSyIezlm9pxRdO5cx4pUO79M6Z48FpO9T4RAZNEvdxA1Tl9wX+5+4JE3cwMAsShNunPCZ884Sd5XM4v0zfRoRLgiXOzaEON/52228Zpw="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "Qpoi2ed8Xr2rszsnR7n13HXj2b1kJ8t/3DSYHe2ZCT390WzoM6gn278gybzW0zKbu2H9hUv5K1oor1h8F0VS/knyK9pNW1Tgx4JRown+ZFzPKyGakoLvKYhHzW2idWzTtZ5AAOet2hJxs056zda2OfUL50pq6cqFbW2c/NtxoDYkuIkB3+xWwuzrkMoAR+gUxvJmr+ADCr1Vo7Uw4KdBcP53dYeWbpO9VcsiWv/8eGWcBHtHJagDdotMtfwePKwKaKwcspbsL6URzrVhW52pEfW5KFqNg7hsiONeVabxuVEvpk+Yi1ngW2s+p4YzO3V4T99mCKqEZXO6cOemwNwF0V1s0U0zmV5uASO8/SwnX/+tgyB7DpYmzR79J+KlY7Qmav4vVa4Ghfri08nbgFSYOJzsPXhoDEg/E9gO9xYZ2A4v0dCH2IOihVGRrvj7zCdgPpSGvrexYlksvnHVBtvTUT1sg6ltAMFtGShnTF2kE2zIjP5HwprHBJ7aBrQLWYMt6jt4IIiD07DuNAzNA8e95rAmjBMmvmiJr2W2aIWrzSOnOlFrQZxhnWH3iY7lsnJEiHU1RXCMqePO+y301kjvSiv386n5FQwbamwnmPz83PGbv8dN3SEBWYW4ONPTjMv+ZWLjvULChpzFGSjOVSytNojSp9rVPLSzPguz3VogGco="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build
script: true

after_success:
- inv hub.push
- inv hub.update-readme
