addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "Us0gHWtfBKPf2Dh/tjvUTdy9zRfCMqnu0L7IuaAjppY9GjyvxNEQxiHZjZfnWryE8/LdfiD3kK6dUuF/G0+YvtPmVhlwTwXZqdsRilQK/FwIbRuPyiEWJlHUf+8FmVHIzi4uSb4FVQGCSS1Z4RTlQS/HD/dpRs9tZ7P/5JzgGjMnHnnyJE8fvVV9Wi+TcQQqMvC0yZt7bJGYSGxCQFTHPYJqE2aqKoijZpAS9ozL4h06mGQrhp7KxUh/4cm+397U3wqVBpAjchDR52JRlTZGuQrkS2HAhyUeRD2EqViEchpdrag5VKawIvJ5zFE2PJupB8Sv+tZOpC8ILJWelfjX56zNynhmumQtarJE5sa3SHaHzb6pm67eUCRQdWtIGHRGIJBEdcYzDCk+5vgZqPzG8l1PaYi+ntV1D8q0g1VjOGYJGoZjlOisyQ4o5nB0BQcRjtCZ/ezyn5fFRlEZm6hoXCIJAcP41fyzUxBI8dYFvzlBtIH/epteG1SCn+0fIW7jaQv4hU9zQiy55Kz35gMkLmwA4/a0ni9qe3v8mT0B/txJMpFE2Ms1tBHraQNMNyoSUi1Vb2GptHYCpHFEA2Q/9PUegRXPIKerkuIMpLjFEMTkmD1IKKwTDUN9P/1m/hEB9LszKbFUBXdI5zAhXh2N+DoUpFkJulO3GmFv9UEex1E="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "FfaPWqEWa5YPYLgWa3gAw+1htHImrmM3R871wg1rp8puxUtQKP+dAlByJo7IBKpZM+EGiSz+Ayv7Yv4E2jUbBh29w7QyojKffe0BnmDxADYtYY8RQ3Dnwv2cbYOG32qyaNwPOxQiqX4dSF31NkHkowHUkoLd4VC6eEKkLj9bAP+bJCqghYi7fbhNjNamDaZyDdqBwM8mdZub4gZmStJg+EfIN2n6RCEAYjxZ8cRWLjY+rl/QEItjPmFVDDzilVvvWJfdVyJGytjQohTkGcFXaa4UzQGzTrUb2eR/l2VPH844QPH/iuFdc0AmzXK15Cf1dN1YsRR2+yrwnSaIIQOJ+89aUkuumAMvPhqdXeW+u5Wwa0jW4ookMg93RZoUzq6UnsRq5nDTHuZU5QB8+Gwae5g0YOTTU3Mvy8sQTbDF64D5Zfg6A4dH7OK17txEW47PGxrXXEExkdIZ6B15RBR/4+XNV/JXkAvwj87Tx1eWFj00el3CrrDE6hhjQAL/8yCqqWOSSFGyZKrqcqpCAS86keXQxti1QzSXoWjMG1GP+H9dp0VM+MQgtLYTvcxte1ELahf/xhNHbwCrHhYwhaw8AmB0my6XcjKxfVOhvY/QtyOduFXSrJiw5tPJEwH6/j4UOTh3iDuKc51wPmM1yOL2HlX4MTr0wyzJZsZPeZ1WuR4="
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build
script: true

after_success:
- inv hub.push
- inv hub.update-readme
