version: '2.3'
services:
  base:
    container_name: bootstrap-base
    build:
      context: images/base
      args:
        TMPLD_VERSION: 0.2.9
        KUBECTL_VERSION: 1.7.8
        KUBECTL_SHA256: c4fd350f9fac76121dda479c1ceba2d339b19f8806aa54207eff55c9c6896724
        KZCONFIG_VERSION: 0.3.3
    image: telephoneorg/bootstrap-base:${DOCKER_TAG:-latest}
  pre-init:
    container_name: bootstrap-pre-init
    build: images/pre-init
    image: telephoneorg/bootstrap-pre-init:${DOCKER_TAG:-latest}
    volumes:
    - $PWD/images/pre-init/config:/bootstrap/config
    - ~/.kube/config:/bootstrap/.kube/config
  post-init:
    container_name: bootstrap-post-init
    build: images/post-init
    image: telephoneorg/bootstrap-post-init:${DOCKER_TAG:-latest}
    volumes:
    - ~/.kube/config:/bootstrap/.kube/config
  config:
    container_name: bootstrap-config
    build: images/config
    image: telephoneorg/bootstrap-config:${DOCKER_TAG:-latest}
    volumes:
    - ~/.kube/config:/bootstrap/.kube/config
