apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-bootstrap-config
  labels:
    project: telephoneorg
    environment: production
spec:
  template:
    metadata:
      name: cluster-bootstrap-config
    spec:
      containers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - rabbitmq
        - couchdb
        - kazoo
        - freeswitch
        - kamailio
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: config
        image: telephoneorg/bootstrap-config:latest
        imagePullPolicy: Always
      restartPolicy: Never
